const METHODS = [
  {
    id: 'smart',
    name: 'SMART 目标法',
    icon: '💎',
    color: '#0891b2',
    category: '目标与行动',
    summary: '把模糊的愿望变成可落地的目标：具体、可衡量、可达、相关、有时限。',
    content: [
      { title: '是什么', text: 'SMART 是目标设定的经典框架，由管理学家 Peter Drucker 推广。它把“我想变好”这种笼统愿望，翻译成可执行、可检验的具体目标。对初学者来说，它最大的好处是——逼你回答“到底怎样才算做到了”。' },
      { title: '为什么有用', text: '大脑面对模糊目标容易拖延；一旦能量化、有期限，行动路径就清晰了，也更容易获得“完成”的正反馈，形成良性循环。' },
      { title: '怎么开始', text: '先随便写一个愿望，再逐条用五要素“审问”它，把含糊处补齐，写成一句话目标。' },
      { title: '常见误区', text: '把“学习”“健身”直接当目标——它们没有衡量标准；或把期限设得太远，失去紧迫感。' },
    ],
    steps: [
      '写下你的原始愿望（先别管格式）。',
      '按 S/M/A/R/T 逐条改写，任何一条说不清就追问“具体指什么、怎么知道完成了”。',
      '把目标写在一处（备忘录 / 本方法练习），并标上截止日。',
      '每周回看一次，完成了打勾，没完成就调细。',
    ],
    tips: [
      '一个目标只解决一件事，贪多容易全崩。',
      '“可达”不等于“轻松”，是“努力后真的能做到”。',
    ],
    example: '把“我想更健康”改成：“每周三、五晚慢跑 30 分钟（S/M），强度以能边跑边说话为准（A/R），连续 8 周后体测心率下降（T）。”',
    relatedTypes: ['self', 'career', 'wellbeing'],
    interactive: true,
    hot: true,
    schema: [
      { key: 'specific', label: 'S 具体', type: 'textarea', placeholder: '目标是什么？要达成什么具体结果？', rows: 2 },
      { key: 'measurable', label: 'M 可衡量', type: 'textarea', placeholder: '如何衡量进度与完成？', rows: 2 },
      { key: 'achievable', label: 'A 可达', type: 'textarea', placeholder: '是否现实？需要哪些资源/支持？', rows: 2 },
      { key: 'relevant', label: 'R 相关', type: 'textarea', placeholder: '为什么这件事对你重要？', rows: 2 },
      { key: 'timebound', label: 'T 有时限', type: 'textarea', placeholder: '何时完成？有哪些关键节点？', rows: 2 },
    ],
    acronym: [
      { letter: 'S', en: 'Specific', zh: '具体的' },
      { letter: 'M', en: 'Measurable', zh: '可衡量的' },
      { letter: 'A', en: 'Achievable', zh: '可达成的' },
      { letter: 'R', en: 'Relevant', zh: '相关的' },
      { letter: 'T', en: 'Time-bound', zh: '有时限的' },
    ],
  },
  {
    id: 'grow',
    name: 'GROW 教练模型',
    icon: '🌳',
    color: '#059669',
    category: '目标与行动',
    summary: 'Goal 目标–Reality 现状–Options 方案–Will 行动，结构化推进从想法到执行。',
    content: [
      { title: '是什么', text: 'GROW 是全球应用最广的教练对话框架，由 John Whitmore 等人系统化。用四个步骤把模糊的议题梳理成清晰行动，初学者也能用它对自己做“自我教练”。' },
      { title: '为什么有用', text: '我们常卡在“想清楚要什么”或“被现状吓住”。GROW 把目标、现状、方案、行动分开谈，避免混在一起越想越乱。' },
      { title: '怎么开始', text: '拿一张纸分四栏，按顺序填，别跳步；尤其 O 阶段先发散、再多评估。' },
      { title: '常见误区', text: '在 O 阶段就急着否定想法；或 W 只写“我会努力”这种没有时间点的空话。' },
    ],
    steps: [
      'G：写出你真正想要的结果（而非“应该”要的）。',
      'R：客观描述现状，包括已具备的条件和真实障碍。',
      'O：列出 3-5 个可能做法，先不评判好坏。',
      'W：选一个做法，写成“周X前做___，做完用___检查”。',
    ],
    tips: [
      'O 阶段数量比质量重要，先让想法冒出来。',
      '如果卡住，假装给朋友出主意往往更清楚。',
    ],
    example: '议题“想换工作”：G=拿到匹配我专业的 offer；R=现在薪资低但技足够；O=内推/猎头/跳槽论坛；W=本周找 2 位前同事内推。',
    relatedTypes: ['self', 'career', 'wellbeing'],
    interactive: true,
    schema: [
      { key: 'goal', label: 'G 目标', type: 'textarea', placeholder: '你想达成什么？定义清晰、具体的成果。', rows: 3 },
      { key: 'reality', label: 'R 现状', type: 'textarea', placeholder: '现在的情况是怎样的？有哪些已具备的条件？', rows: 3 },
      { key: 'options', label: 'O 方案', type: 'textarea', placeholder: '有哪些可能的做法？先发散，不急着评判。', rows: 3 },
      { key: 'will', label: 'W 行动', type: 'textarea', placeholder: '你具体要做什么？何时开始？如何让自己负责？', rows: 3 },
    ],
    acronym: [
      { letter: 'G', en: 'Goal', zh: '目标' },
      { letter: 'R', en: 'Reality', zh: '现状' },
      { letter: 'O', en: 'Options', zh: '方案' },
      { letter: 'W', en: 'Will', zh: '行动意愿' },
    ],
  },
  {
    id: 'woop',
    name: 'WOOP 心理对照法',
    icon: '💡',
    color: '#ca8a04',
    category: '目标与行动',
    summary: 'Wish–Outcome–Obstacle–Plan：用“心理对照”把障碍提前想清楚，提升行动力。',
    content: [
      { title: '是什么', text: 'WOOP 由纽约大学 Oettingen 教授基于“心理对照”研究提出：先想愿望和好结果，再认真想内部障碍，最后写“如果…就…”计划。' },
      { title: '为什么有用', text: '只幻想成功反而会消耗动力；而“先想障碍再预案”能让大脑在真遇到阻碍时自动触发应对。研究证明它比单纯立志更有效。' },
      { title: '怎么开始', text: '选一个近期想改的小习惯，按四步写下来，重点把 Plan 写成 if-then。' },
      { title: '常见误区', text: '把 Obstacle 写成外部借口（“没时间”）；WOOP 更强调你自己的内部阻力（拖延、怕麻烦）。Plan 不具体就等于没写。' },
    ],
    steps: [
      'W：写下一个你真心想做的改变。',
      'O1：想象它实现后最好的画面 / 感受。',
      'O2：写出最可能出现的“自己这边的”阻碍。',
      'P：写“如果[障碍]出现，那么我就[具体动作]”。',
    ],
    tips: [
      'Plan 越具体、越能在 1 分钟内做，越有效。',
      '每天起床或睡前在心里过一遍 Plan，形成触发。',
    ],
    example: 'W=每天读书；O2=晚上刷手机忘了；P=“如果拿起手机前还没读书，那么我先读 5 页再刷。”',
    relatedTypes: ['self', 'wellbeing', 'career'],
    interactive: true,
    hot: true,
    schema: [
      { key: 'wish', label: 'W 愿望', type: 'textarea', placeholder: '你最想做出的一项改变是什么？', rows: 2 },
      { key: 'outcome', label: 'O 结果', type: 'textarea', placeholder: '设想它实现后最好的结果、你的感受？', rows: 2 },
      { key: 'obstacle', label: 'O 障碍', type: 'textarea', placeholder: '最可能出现的内部阻碍是什么？（如拖延、怕失败）', rows: 2 },
      { key: 'plan', label: 'P 计划', type: 'textarea', placeholder: '如果[障碍]出现，那么我就[具体应对]？', rows: 2 },
    ],
    acronym: [
      { letter: 'W', en: 'Wish', zh: '愿望' },
      { letter: 'O', en: 'Outcome', zh: '结果' },
      { letter: 'O', en: 'Obstacle', zh: '障碍' },
      { letter: 'P', en: 'Plan', zh: '计划' },
    ],
  },
  {
    id: 'pomodoro',
    name: '番茄工作法',
    icon: '🍅',
    color: '#dc2626',
    category: '目标与行动',
    summary: '25 分钟专注 + 5 分钟休息的节奏法，降低拖延、提升专注。',
    content: [
      { title: '是什么', text: '由 Francesco Cirillo 在 1980 年代发明（他用番茄形计时器得名）。把工作切成 25 分钟高度专注的“番茄钟”，钟间短暂休息。' },
      { title: '为什么有用', text: '它把“大任务”变成一个个可完成的小单元，降低启动门槛；固定休息也防止倦怠，让专注可持续。' },
      { title: '怎么开始', text: '选一项任务，设 25 分钟计时只做它，响铃休息 5 分钟，每 4 个番茄长休 15-30 分钟。' },
      { title: '常见误区', text: '番茄钟内回消息 / 刷网页——一旦切换，这个番茄就废了；或把时长硬套到需要深度沉浸的创作上。' },
    ],
    steps: [
      '列今天要做的 1-3 件任务。',
      '设 25 分钟计时，期间只做当前任务，杂念先记纸上。',
      '响铃后强制休息 5 分钟（离开屏幕最好）。',
      '每完成 4 个番茄，长休一次并回顾进度。',
    ],
    tips: [
      '被打断就记下来、稍后处理，别当场处理。',
      '难度大的任务先用 1 个番茄“破冰”，往往就接上了。',
    ],
    example: '写报告拖延？设番茄钟 25 分钟只写大纲，休息 5 分钟，再一个番茄写正文——三四个番茄就能出初稿。',
    relatedTypes: ['self', 'career'],
    interactive: true,
    hot: true,
    schema: [
      { key: 'task', label: '今日任务', type: 'textarea', placeholder: '选 1-3 件今天要专注完成的事', rows: 2 },
      { key: 'count', label: '番茄目标', type: 'textarea', placeholder: '打算完成几个番茄钟？（每个 25 分钟）', rows: 2 },
      { key: 'reflect', label: '一轮复盘', type: 'textarea', placeholder: '结束后写：哪个番茄最顺、哪个被中断了', rows: 2 },
    ],
  },
  {
    id: 'pdca',
    name: 'PDCA 循环',
    icon: '🔄',
    color: '#0d9488',
    category: '目标与行动',
    summary: 'Plan 计划–Do 执行–Check 检查–Act 处理，持续改进的质量循环。',
    content: [
      { title: '是什么', text: 'PDCA（计划-执行-检查-处理）源自休哈特、由戴明推广的质量管理循环，也极适合个人成长：在“做→看→改”里持续迭代。' },
      { title: '为什么有用', text: '很多人“做了就完了”。PDCA 强制你回看效果并标准化有效动作，避免重复踩坑、原地打转。' },
      { title: '怎么开始', text: '针对一个小目标跑一轮：先计划，小范围试，检查偏差，把有效的固定下来、无效的改掉，再进下一轮。' },
      { title: '常见误区', text: '只有 P 和 D，没有 C/A，等于没有循环；或一次想改太大，检查不出因果。' },
    ],
    steps: [
      'P：定一个小目标 + 具体做法。',
      'D：小范围执行（先试一周）。',
      'C：对照目标看结果，哪里偏了。',
      'A：有效的变成习惯，无效的调整方案，进入下一轮。',
    ],
    tips: [
      '每轮只改一个变量，才看得清什么管用。',
      '“处理”那一步最易被省，但它才是进步来源。',
    ],
    example: '想早睡：P=23 点前放下手机；D=试一周；C=发现刷视频到 1 点；A=把手机放客厅充电，下周再测。',
    relatedTypes: ['career', 'self'],
    interactive: true,
    schema: [
      { key: 'plan', label: 'P 计划', type: 'textarea', placeholder: '定一个小目标与具体做法', rows: 2 },
      { key: 'do', label: 'D 执行', type: 'textarea', placeholder: '小范围试做（先试一周）', rows: 2 },
      { key: 'check', label: 'C 检查', type: 'textarea', placeholder: '对照目标，哪里偏了？', rows: 2 },
      { key: 'act', label: 'A 处理', type: 'textarea', placeholder: '有效的变习惯，无效的怎么改？', rows: 2 },
    ],
    acronym: [
      { letter: 'P', en: 'Plan', zh: '计划' },
      { letter: 'D', en: 'Do', zh: '执行' },
      { letter: 'C', en: 'Check', zh: '检查' },
      { letter: 'A', en: 'Act', zh: '处理' },
    ],
  },
  {
    id: 'abc',
    name: 'ABC 认知重构',
    icon: '🔤',
    color: '#7c3aed',
    category: '情绪与认知',
    summary: '基于 REBT：情绪不是事件直接造成，而是我们对事件的信念造成。',
    content: [
      { title: '是什么', text: 'ABC 来自 Ellis 的理性情绪行为疗法（REBT）。A 事件→B 信念→C 情绪后果，并加 D 辩驳、E 新结果。它说明：伤你的往往不是事，而是你对事的想法。' },
      { title: '为什么有用', text: '负面情绪出现时，我们习惯怪“外因”；ABC 帮你定位到“我当时在想什么”，从而有机会换一个更合理的想法，情绪随之改变。' },
      { title: '怎么开始', text: '情绪低落时随手记 A/B/C，再对 B 做 D 辩驳：证据充分吗？有别的解释吗？最后写 E。' },
      { title: '常见误区', text: '把 B 写成事实（“他就是针对我”）而非想法；或 D 只说“别想了”这种无效安慰。' },
    ],
    steps: [
      'A：记下客观发生的事（不加评判）。',
      'B：写下你当时对自己说的那句话。',
      'C：你的情绪 / 行为反应是什么。',
      'D→E：质疑 B 的证据，写出更合理的解读与新结果。',
    ],
    tips: [
      '区分“事实”和“我对事实的讲述”，后者才是可改的。',
      '多问“朋友遇到同样事，我会怎么跟他解释”。',
    ],
    example: 'A=同事没回消息；B=“他肯定讨厌我”；C=焦虑；D=“他可能在开会”；E=松了口气，晚点再问。',
    relatedTypes: ['mood', 'stress', 'wellbeing'],
    interactive: true,
    hot: true,
    schema: [
      { key: 'event', label: 'A 事件', type: 'textarea', placeholder: '发生了什么？（客观事实）', rows: 2 },
      { key: 'belief', label: 'B 信念', type: 'textarea', placeholder: '你当时在想什么？对自己说了什么？', rows: 2 },
      { key: 'consequence', label: 'C 后果', type: 'textarea', placeholder: '你的情绪与行为反应是什么？', rows: 2 },
      { key: 'dispute', label: 'D 辩驳', type: 'textarea', placeholder: '这个想法证据充分吗？有没有更合理的解释？', rows: 2 },
      { key: 'newresult', label: 'E 新结果', type: 'textarea', placeholder: '辩驳后，你的情绪/行为有什么变化？', rows: 2 },
    ],
    acronym: [
      { letter: 'A', en: 'Activating event', zh: '诱发事件' },
      { letter: 'B', en: 'Belief', zh: '信念' },
      { letter: 'C', en: 'Consequence', zh: '情绪后果' },
      { letter: 'D', en: 'Disputation', zh: '辩驳' },
      { letter: 'E', en: 'Effect', zh: '新效果' },
    ],
  },
  {
    id: 'threegood',
    name: '三件好事',
    icon: '🙏',
    color: '#16a34a',
    category: '情绪与认知',
    summary: '每天记录三件好事并写出原因，训练大脑留意积极面（Seligman 积极心理学练习）。',
    content: [
      { title: '是什么', text: '“三件好事”由积极心理学之父 Seligman 在研究中推广：连续一段时间，每天写下三件好事并写出原因。' },
      { title: '为什么有用', text: '大脑天生更留意问题（负向偏差）。这个练习像“注意力训练”，把镜头转向当天顺利 / 温暖的小事，长期可提升积极情绪与生活满意度。' },
      { title: '怎么开始', text: '睡前回顾当天，写 3 件进展不错或让你开心的事，每件补一句“为什么会发生”。' },
      { title: '常见误区', text: '等“大好事”才写，结果常空白；其实越小越具体越有效（一杯好喝的咖啡也算）。' },
    ],
    steps: [
      '固定一个时间（如睡前）。',
      '写 3 件今天发生的小确幸。',
      '每件追问“为什么会发生 / 和我有关吗”。',
      '坚持 1-2 周，感受注意力变化。',
    ],
    tips: [
      '不必惊天动地，“准时下班”“猫蹭了我”都算。',
      '写“原因”这一步才是关键，它训练你看到自己的作用。',
    ],
    example: '①同事分享了零食（因为我对人友好）；②准时下班（因为我提前规划）；③天气好去散步（因为我留了时间）。',
    relatedTypes: ['wellbeing', 'mood', 'self'],
    interactive: true,
    hot: true,
    schema: [
      { key: 'good1', label: '好事 1', type: 'textarea', placeholder: '今天发生的好事？为什么会发生？', rows: 2 },
      { key: 'good2', label: '好事 2', type: 'textarea', placeholder: '第二件好事？为什么会发生？', rows: 2 },
      { key: 'good3', label: '好事 3', type: 'textarea', placeholder: '第三件好事？为什么会发生？', rows: 2 },
      { key: 'note', label: '今日感悟', type: 'textarea', placeholder: '今天整体的情绪或一句话总结（选填）。', rows: 2 },
    ],
  },
  {
    id: 'mindful',
    name: '正念呼吸',
    icon: '🫧',
    color: '#0891b2',
    category: '情绪与认知',
    summary: '把注意力放回呼吸的觉察练习，帮助从焦虑与反刍中抽离、回到当下。',
    content: [
      { title: '是什么', text: '正念（Mindfulness）源自卡巴金创立的 MBSR 减压课程：不加评判地觉察当下。呼吸是最常用的“锚点”，因为它随时都在。' },
      { title: '为什么有用', text: '焦虑和反复想（反刍）往往是对过去或未来的纠缠；把注意力放回呼吸，等于给过度思考按下暂停键，和长期降低应激反应有关。' },
      { title: '怎么开始', text: '坐稳、闭眼或垂视，把注意力轻轻放在一呼一吸上；走神了，就温柔地拉回来——拉回本身就是在练。' },
      { title: '常见误区', text: '追求“完全不想”（不可能）；或觉得“没感觉 = 没用”。正念是觉察，不是清空。' },
    ],
    steps: [
      '找个不被打扰的 3-5 分钟。',
      '舒适坐好，眼睛微闭。',
      '感受呼吸进出，可数吸 1 呼 2…到 10 再循环。',
      '发现走神，不批评，把注意放回呼吸。',
    ],
    tips: [
      '从 3 分钟开始，比“立誓冥想 30 分”更易坚持。',
      '等车、排队也能做“三次深呼吸”的微正念。',
    ],
    example: '睡前念头翻涌睡不着？不做“快睡”的努力，只数呼吸，通常几分钟后身体先松下来。',
    relatedTypes: ['mood', 'stress', 'sleep'],
    interactive: true,
    schema: [
      { key: 'duration', label: '练习时长', type: 'textarea', placeholder: '今天正念呼吸做了几分钟？', rows: 2 },
      { key: 'anchor', label: '注意力锚点', type: 'textarea', placeholder: '你用什么把注意力拉回当下？（呼吸 / 身体感受）', rows: 2 },
      { key: 'note', label: '当下感受', type: 'textarea', placeholder: '练习后身体 / 情绪有什么变化？', rows: 2 },
    ],
  },
  {
    id: 'nvc',
    name: '非暴力沟通',
    icon: '💬',
    color: '#be185d',
    category: '情绪与认知',
    summary: '观察–感受–需要–请求：用四步表达，减少防御与冲突，增进理解。',
    content: [
      { title: '是什么', text: '非暴力沟通（NVC）由 Marshall Rosenberg 提出，把表达拆成 观察-感受-需要-请求 四步，目标是减少评判与防御，增进理解。' },
      { title: '为什么有用', text: '很多冲突来自“一开口就是评价 / 指责”，对方立刻防卫。NVC 先说事实与感受，再讲需要，把对抗变成协作。' },
      { title: '怎么开始', text: '说话前在心里分四步：我看到了什么（观察）、我感觉如何（感受）、我需要什么（需要）、我希望怎样（请求）。' },
      { title: '常见误区', text: '把“你总是不回消息”（评价）当观察；或把“请求”说成“命令”（你必须）。' },
    ],
    steps: [
      '观察：说事实，不贴标签（“这周你晚了 3 次”而非“你总迟到”）。',
      '感受：表达情绪，不怪对方（“我有点不安”）。',
      '需要：说出未被满足的需要（“我需要可预期”）。',
      '请求：具体、可执行的动作（“下次能否提前说一声？”）。',
    ],
    tips: [
      '“感受”是情绪词（孤单、着急），不是想法（觉得你不在乎）。',
      '请求要可验证，别用模糊的“对我好一点”。',
    ],
    example: '伴侣沉迷游戏：观察“你今晚玩了 3 小时”；感受“我有点孤单”；需要“陪伴”；请求“明晚我们聊半小时天好吗？”',
    relatedTypes: ['social', 'self', 'mood'],
    interactive: true,
    schema: [
      { key: 'observe', label: 'O 观察', type: 'textarea', placeholder: '客观发生了什么？（不加评判）', rows: 2 },
      { key: 'feel', label: 'F 感受', type: 'textarea', placeholder: '你当下的情绪是什么？', rows: 2 },
      { key: 'need', label: 'N 需要', type: 'textarea', placeholder: '你未被满足的需要是什么？', rows: 2 },
      { key: 'request', label: 'R 请求', type: 'textarea', placeholder: '你希望对方具体做什么？', rows: 2 },
    ],
    acronym: [
      { letter: 'O', en: 'Observation', zh: '观察（事实）' },
      { letter: 'F', en: 'Feeling', zh: '感受（情绪）' },
      { letter: 'N', en: 'Need', zh: '需要' },
      { letter: 'R', en: 'Request', zh: '请求' },
    ],
  },
  {
    id: 'festinger',
    name: '费斯汀格法则',
    icon: '⚖️',
    color: '#4338ca',
    category: '情绪与认知',
    summary: '生活中 10% 是事件，90% 是你对事件的反应——掌控反应即掌控情绪。',
    content: [
      { title: '是什么', text: '心理学家 Leon Festinger 提出：我们感到的困扰，大约只有 10% 来自事情本身，90% 来自我们对事情的反应。' },
      { title: '为什么有用', text: '它把“情绪的主控权”还给你——事件常常不可控，但解读与应对是你能选的。同一件事，不同反应结局天差地别。' },
      { title: '怎么开始', text: '当事情出错，先停顿几秒，问自己“我能控制的只是我的反应”，把能量放在建设性的下一步。' },
      { title: '常见误区', text: '误读成“都是我想太多”——有些事确实该解决；法则是提醒你别在“不可控”上内耗。' },
    ],
    steps: [
      '事件发生的瞬间，先深呼吸停下。',
      '区分：这是我能控制的，还是不能控制的？',
      '把注意力从“为什么是我”转到“我现在能做什么”。',
      '选一个最小的建设性动作先动起来。',
    ],
    tips: [
      '10/90 是比喻，不是精确比例，重在“反应可练”。',
      '真遇到不公，行动解决问题，同时管理好自己的情绪。',
    ],
    example: '重要会议前咖啡洒了：不可控的是已洒；可控的是“换件衣、准时到场、专注议题”，而不是反复懊恼。',
    relatedTypes: ['mood', 'stress', 'self'],
    interactive: true,
    schema: [
      { key: 'event', label: '事件', type: 'textarea', placeholder: '发生了什么？（那 10% 的事）', rows: 2 },
      { key: 'reaction', label: '我的反应', type: 'textarea', placeholder: '你当时是怎么反应的？（那 90% 的反应）', rows: 2 },
      { key: 'next', label: '建设性下一步', type: 'textarea', placeholder: '可控的部分，你能做的最小行动是什么？', rows: 2 },
    ],
  },
  {
    id: 'fogg',
    name: 'Fogg 行为模型',
    icon: '🔧',
    color: '#0d9488',
    category: '习惯与行为',
    summary: 'B=MAP：行为发生需要动机、能力、提示三者同时具备。',
    content: [
      { title: '是什么', text: '斯坦福 BJ Fogg 的行为模型：行为 B = 动机(Motivation) × 能力(Ability) × 提示(Prompt)，三者同时出现，行为才会发生。' },
      { title: '为什么有用', text: '想改习惯却总失败，常是因为只盯“意志力”。Fogg 告诉你：动机不够时，就降低难度、加明显提示——不必硬扛。' },
      { title: '怎么开始', text: '对目标行为打分：动机强不强？做起来难不难？有没有触发？哪块弱就补哪块。' },
      { title: '常见误区', text: '只在“打鸡血”（提动机）上用力；动机最低的日子里，再强的意愿也撑不住，要靠“极简 + 提示”。' },
    ],
    steps: [
      '写清目标行为（一句话）。',
      '评估动机(1-10)与能力(1-10)。',
      '设计一个明确提示（固定时间 / 地点 / 既有的动作）。',
      '若动机低，优先把行为缩到“小到不可能失败”。',
    ],
    tips: [
      '动机和能力可互相补：高动机能扛低能力，低动机必须极低门槛 + 强提示。',
      '提示要“刚好在行动现场”，别指望记得。',
    ],
    example: '想喝水：动机一般、接水容易(高能力)、把水杯放显示器旁(强提示)→自然就喝。',
    relatedTypes: ['self', 'wellbeing', 'career'],
    interactive: true,
    schema: [
      { key: 'behavior', label: '目标行为', type: 'textarea', placeholder: '你想养成或改变的一个具体行为？', rows: 2 },
      { key: 'motivation', label: '动机强度', type: 'scale', min: 1, max: 10, placeholder: '你做它的意愿有多强？（1-10）' },
      { key: 'ability', label: '容易程度', type: 'scale', min: 1, max: 10, placeholder: '做起来有多容易？（1-10，越高越容易）' },
      { key: 'prompt', label: '提示设计', type: 'textarea', placeholder: '用什么触发来提醒自己执行？（如固定时间/地点/既有动作）', rows: 2 },
      { key: 'design', label: '行动方案', type: 'textarea', placeholder: '如何让行为更容易发生？先从小到不可能失败的一步开始。', rows: 2 },
    ],
    acronym: [
      { letter: 'B', en: 'Behavior', zh: '行为' },
      { letter: 'M', en: 'Motivation', zh: '动机' },
      { letter: 'A', en: 'Ability', zh: '能力' },
      { letter: 'P', en: 'Prompt', zh: '提示' },
    ],
  },
  {
    id: 'tinyhabits',
    name: '微习惯',
    icon: '🌰',
    color: '#16a34a',
    category: '习惯与行为',
    summary: '把目标缩到“小到不可能失败”的一步，用锚点习惯串联，轻松启动。',
    content: [
      { title: '是什么', text: '微习惯是 Fogg 提出的方法：把新习惯缩到 30 秒内、几乎零门槛的动作，并“锚定”在一个已有习惯之后。' },
      { title: '为什么有用', text: '启动阻力与完美主义是习惯杀手。微行为小到不可能失败，先让“做”发生，再借成就感逐步放大。' },
      { title: '怎么开始', text: '写一句“在[既有习惯]之后，我会[微行为]”，做完给自己一个肯定（庆祝）。' },
      { title: '常见误区', text: '一上来就设大目标（每天 50 个俯卧撑）会吓退自己；微习惯要“小到害羞”才对。' },
    ],
    steps: [
      '选一个你想培养的方向。',
      '缩成 30 秒内、零门槛的动作。',
      '找到锚点：“刷完牙后”“关灯后”。',
      '完成后说句鼓励或比个耶，强化正反馈。',
    ],
    tips: [
      '微行为可以之后自然长大，但起点一定要小。',
      '“庆祝”很重要，它给大脑一个“这感觉不错”的标记。',
    ],
    example: '想运动：锚点“刷完牙后，我做 2 个深蹲”，做完比个耶。几周后可能变成 10 个。',
    relatedTypes: ['self', 'wellbeing'],
    interactive: true,
    schema: [
      { key: 'behavior', label: '微行为', type: 'textarea', placeholder: '想培养的方向，缩成 30 秒内、零门槛的动作', rows: 2 },
      { key: 'anchor', label: '锚点习惯', type: 'textarea', placeholder: '在哪个已有习惯之后做它？（如刷完牙后）', rows: 2 },
      { key: 'celebrate', label: '庆祝动作', type: 'textarea', placeholder: '完成后怎么给自己一个肯定？（如比个耶）', rows: 2 },
    ],
  },
  {
    id: 'eisenhower',
    name: '四象限法则',
    icon: '⏱️',
    color: '#ea580c',
    category: '习惯与行为',
    summary: '按“重要/紧急”把事务分四格，优先做重要不紧急的事。',
    content: [
      { title: '是什么', text: '基于艾森豪威尔的思路：用“重要 / 紧急”两个维度把事务分成四象限，帮你看清该把时间花在哪。' },
      { title: '为什么有用', text: '我们常被“紧急”牵着走，忽略真正决定长期结果的“重要不紧急”事（健康、关系、学习）。' },
      { title: '怎么开始', text: '把待办逐条放进四格，重点保护第二象限，给第一象限设截止、给第三委托、给第四削减。' },
      { title: '常见误区', text: '把所有事都当“重要紧急”去救火；或长期忽视第二象限直到它变成危机。' },
    ],
    steps: [
      '列出近期所有任务。',
      '逐个判断：重要吗？紧急吗？放入对应象限。',
      '①立刻做；②排进日程重点做；③尽量委托 / 批量；④减少或不做。',
      '每天先看第二象限，别等它着火。',
    ],
    tips: [
      '第二象限（重要不紧急）是“预防”，最值得投资。',
      '给任务标“截止时间”能防止第一象限爆炸。',
    ],
    example: '①项目明天的截止（做）；②健身/学外语（排每周固定时段）；③临时杂事（集中处理）；④无谓刷手机（削减）。',
    relatedTypes: ['self', 'career'],
    interactive: true,
    schema: [
      { key: 'task', label: '待办清单', type: 'textarea', placeholder: '列出近期所有任务', rows: 3 },
      { key: 'q1', label: '重要且紧急', type: 'textarea', placeholder: '第一象限：立刻做', rows: 2 },
      { key: 'q2', label: '重要不紧急', type: 'textarea', placeholder: '第二象限：排进日程重点做', rows: 2 },
      { key: 'q3', label: '紧急不重要', type: 'textarea', placeholder: '第三象限：委托 / 批量', rows: 2 },
      { key: 'q4', label: '不重要不紧急', type: 'textarea', placeholder: '第四象限：减少 / 不做', rows: 2 },
    ],
  },
  {
    id: 'pareto',
    name: '二八定律',
    icon: '📈',
    color: '#b45309',
    category: '习惯与行为',
    summary: '约 80% 的结果来自 20% 的关键投入，聚焦高杠杆事项。',
    content: [
      { title: '是什么', text: '帕累托法则（二八定律）：在许多领域，约 20% 的原因产生 80% 的结果。' },
      { title: '为什么有用', text: '它提醒你精力有限：与其平均用力，不如先找到那 20% 的高产出部分，把力气花在杠杆点上。' },
      { title: '怎么开始', text: '盘点你的任务 / 客户 / 时间，找出那 20% 高产出部分，优先投入；对低效的多数做减法或自动化。' },
      { title: '常见误区', text: '死磕 80/20 的精确比例；它只是提醒“少数因素主导结果”，用来识别重点，而非绝对标准。' },
    ],
    steps: [
      '列出你近期投入的事 / 人 / 渠道。',
      '标出哪些产出了大部分价值（那 20%）。',
      '优先给它们时间与资源。',
      '对低效的多数，做减法、委托或自动化。',
    ],
    tips: [
      '比例不必然精确是 80/20，重点是“抓关键少数”。',
      '定期复评，高产出部分会随阶段变化。',
    ],
    example: '销售发现 20% 客户贡献 80% 业绩→把跟进重点放在这批客户，其余用模板化跟进。',
    relatedTypes: ['career', 'self'],
    interactive: true,
    schema: [
      { key: 'list', label: '投入盘点', type: 'textarea', placeholder: '列出你的任务 / 客户 / 时间渠道', rows: 3 },
      { key: 'top', label: '关键 20%', type: 'textarea', placeholder: '哪些产出了大部分价值？', rows: 2 },
      { key: 'cut', label: '可减法项', type: 'textarea', placeholder: '低效的多数，如何做减法 / 自动化？', rows: 2 },
    ],
  },
  {
    id: 'johari',
    name: '乔哈里视窗',
    icon: '🪟',
    color: '#7c3aed',
    category: '自我与成长',
    summary: '公开/盲点/隐藏/未知四个象限，用反馈与自我暴露扩大“公开区”。',
    content: [
      { title: '是什么', text: '乔哈里视窗（Johari Window）用四个象限描述「我与人」之间的自我认知：公开区（人知我知）、盲点区（人知我不知）、隐藏区（我知人不知）、未知区（人我都不知）。' },
      { title: '为什么有用', text: '很多关系与协作摩擦，来自「我以为的你」和「真实的你」不一致。把它画出来，你能看到差距在哪、往哪补。' },
      { title: '怎么开始', text: '主动请信任的人给反馈（缩盲点），并适度分享真实想法（缩隐藏），两块一缩，「公开区」变大，信任更顺。' },
      { title: '常见误区', text: '把隐藏区全敞开（过度自我暴露反而累）；或拒绝任何反馈（盲点永远在）。' },
    ],
    steps: [
      '画出四个象限。',
      '请 1-2 位信任的人，告诉你在他们眼中你的特点（填盲点区）。',
      '选一两件一直没说的事，适度对合适的人讲出来（缩隐藏区）。',
      '看公开区是否变大，关系是否更顺。',
    ],
    tips: [
      '反馈要找「愿意对你诚实且善意」的人。',
      '自我暴露讲究对象和节奏，不是越多越好。',
    ],
    example: '你自认「外向」，但同事反馈你开会很少发言（盲点）；你又一直没说「其实准备发言会紧张」（隐藏）。说开后，大家反而更包容。',
    relatedTypes: ['social', 'self', 'personality'],
    interactive: true,
    schema: [
      { key: 'open', label: '公开区', type: 'textarea', placeholder: '别人知道、你也知道的优点/特点？', rows: 2 },
      { key: 'blind', label: '盲点区', type: 'textarea', placeholder: '你不太察觉、但别人可能注意到的？', rows: 2 },
      { key: 'hidden', label: '隐藏区', type: 'textarea', placeholder: '你隐瞒、尚未对他人说的？（选填）', rows: 2 },
      { key: 'unknown', label: '未知区', type: 'textarea', placeholder: '你想探索的潜能或盲区？', rows: 2 },
    ],
    acronym: [
      { letter: 'Open', en: 'Open Area', zh: '公开区（人知我知）' },
      { letter: 'Blind', en: 'Blind Spot', zh: '盲点区（人知我不知）' },
      { letter: 'Hidden', en: 'Hidden Area', zh: '隐藏区（我知人不知）' },
      { letter: 'Unknown', en: 'Unknown Area', zh: '未知区（人我都不知）' },
    ],
  },
  {
    id: 'perma',
    name: 'PERMA 积极心理学',
    icon: '🌈',
    color: '#db2777',
    category: '自我与成长',
    summary: '积极情绪、投入、关系、意义、成就——幸福五要素自评与练习。',
    content: [
      { title: '是什么', text: 'PERMA 是 Seligman 把「幸福」拆成的五个可培养元素：P 积极情绪、E 投入、R 关系、M 意义、A 成就。' },
      { title: '为什么有用', text: '幸福不是「一直开心」这种单一情绪，而是多维度均衡。哪块长期空缺，整体满意度都会掉。' },
      { title: '怎么开始', text: '对五个维度各 1-10 自评，找出最弱的一环，针对性安排一个小活动（关系弱就约朋友，意义弱就做件利他的事）。' },
      { title: '常见误区', text: '只追 P（及时行乐）忽略 M/A；或把成就全押在工作上，别处空着。' },
    ],
    steps: [
      '给 P/E/R/M/A 各打 1-10 分。',
      '圈出最低的一两项。',
      '为每项写 1 个本周可做的小行动。',
      '下周复评，看分数有无变化。',
    ],
    tips: [
      '五个维度都重要，但可以先补最短板。',
      '意义感常来自「对别人有用」，不一定宏大。',
    ],
    example: '自评分 P8 E7 R4 M5 A6：关系偏弱，本周约老朋友吃饭；意义偏弱，周末做 2 小时志愿。',
    relatedTypes: ['wellbeing', 'mood', 'self'],
    interactive: true,
    schema: [
      { key: 'positive', label: 'P 积极情绪', type: 'scale', min: 1, max: 10, placeholder: '近期体验愉悦/满足的程度（1-10）' },
      { key: 'engagement', label: 'E 投入', type: 'scale', min: 1, max: 10, placeholder: '专注忘我做事的程度（1-10）' },
      { key: 'relationship', label: 'R 关系', type: 'scale', min: 1, max: 10, placeholder: '与他人联结/被支持的程度（1-10）' },
      { key: 'meaning', label: 'M 意义', type: 'scale', min: 1, max: 10, placeholder: '觉得所作所为有意义程度（1-10）' },
      { key: 'accomplishment', label: 'A 成就', type: 'scale', min: 1, max: 10, placeholder: '达成目标/有成就感程度（1-10）' },
      { key: 'note', label: '薄弱项计划', type: 'textarea', placeholder: '最弱的一项打算如何加强？（选填）', rows: 2 },
    ],
    acronym: [
      { letter: 'P', en: 'Positive emotion', zh: '积极情绪' },
      { letter: 'E', en: 'Engagement', zh: '投入' },
      { letter: 'R', en: 'Relationships', zh: '关系' },
      { letter: 'M', en: 'Meaning', zh: '意义' },
      { letter: 'A', en: 'Accomplishment', zh: '成就' },
    ],
  },
  {
    id: 'growth',
    name: '成长型思维',
    icon: '🌿',
    color: '#059669',
    category: '自我与成长',
    summary: '能力可通过努力与策略发展，把“我不行”换成“我还没学会”。',
    content: [
      { title: '是什么', text: '成长型思维由 Dweck 提出：固定型思维认为能力天生，成长型思维认为能力可经练习生长。' },
      { title: '为什么有用', text: '它改变你面对困难时的「内心台词」。把「我不行」换成「我还没学会」，失败就从「否定我」变成「信息反馈」。' },
      { title: '怎么开始', text: '每当脱口而出「我做不到」，补一句「……目前还不会，需要___」；把挑战当练习而非对智力的审判。' },
      { title: '常见误区', text: '误以为「夸努力就行」于是无脑鼓励；或把成长型当「只要想就能」，忽略策略与方法同样重要。' },
    ],
    steps: [
      '注意自己说「我不行 / 我笨」的时刻。',
      '改成「我现在还不会，需要___」。',
      '复盘失败时说「我学到了___」，而不是「我失败了」。',
      '夸努力与策略，不夸「你真聪明」。',
    ],
    tips: [
      '成长型不是否定天赋，而是「天赋是起点，练习决定上限」。',
      '对「暂时不会」保持耐心，进步常是非线性的。',
    ],
    example: '学新软件总出错：固定思维「我没那天赋」；成长思维「我还不会，先跟教程做 3 遍，再总结步骤」。',
    relatedTypes: ['self', 'wellbeing', 'career'],
    interactive: true,
    schema: [
      { key: 'fixed', label: '固定型内心台词', type: 'textarea', placeholder: '最近一次说「我不行 / 我笨」是在什么事上？', rows: 2 },
      { key: 'reframe', label: '成长型改写', type: 'textarea', placeholder: '把它改成「我还不会，需要___」', rows: 2 },
      { key: 'learn', label: '这次学到', type: 'textarea', placeholder: '如果失败了，你能提炼出什么信息？', rows: 2 },
    ],
  },
  {
    id: 'flow',
    name: '心流',
    icon: '🌊',
    color: '#0891b2',
    category: '自我与成长',
    summary: '挑战与技能匹配时进入的完全专注状态，是高效与幸福的来源。',
    content: [
      { title: '是什么', text: '心流由 Csikszentmihalyi 提出：当任务挑战与自身技能大致匹配，人会进入忘我、时间感改变的深度专注状态。' },
      { title: '为什么有用', text: '心流既是高效来源，也是幸福来源——你在「刚好有点难」的事里最投入，也最容易忘记烦恼。' },
      { title: '怎么开始', text: '主动调节难度：太易会无聊、太难会焦虑；给任务设清晰小目标和即时反馈，更容易滑入心流。' },
      { title: '常见误区', text: '以为「越难越好」；其实难度远超技能会焦虑，远低于技能会走神，匹配才是关键。' },
    ],
    steps: [
      '选一件你有点基础、又不太轻松的事。',
      '把它拆成有明确终点的小目标。',
      '排除干扰（手机静音），进入连续操作。',
      '事后记「这次为什么顺」，复刻条件。',
    ],
    tips: [
      '心流常见于爱好 / 创作 / 运动，也可刻意迁移到工作。',
      '目标清晰 + 反馈及时，是进入心流的两大开关。',
    ],
    example: '写代码卡壳（太难）→ 先拆成「先跑通最小例子」（匹配），进入忘了吃饭的状态。',
    relatedTypes: ['wellbeing', 'self'],
    interactive: true,
    schema: [
      { key: 'task', label: '选定任务', type: 'textarea', placeholder: '选一件你有点基础、又不太轻松的事', rows: 2 },
      { key: 'goal', label: '清晰小目标', type: 'textarea', placeholder: '把它拆成有明确终点的小目标', rows: 2 },
      { key: 'note', label: '心流条件', type: 'textarea', placeholder: '这次为什么顺 / 不顺？怎样更容易进入状态？', rows: 2 },
    ],
  },
  {
    id: 'wheel',
    name: '人生平衡轮',
    icon: '🎡',
    color: '#ca8a04',
    category: '自我与成长',
    summary: '从多个生活维度打分，看见失衡处，制定补强行动。',
    content: [
      { title: '是什么', text: '人生平衡轮把生活分成若干维度（健康、事业、关系、成长、娱乐等），每个 1-10 打分并连成「轮子」，直观看哪里瘸腿。' },
      { title: '为什么有用', text: '我们常在某块拼命（如工作），却忽略其他在悄悄塌方。轮子一画，失衡一眼可见，优先补最瘸的那块。' },
      { title: '怎么开始', text: '先给各维度打分，找出最低几项，各写 1 个可落地的小动作，下周复评看是否回升。' },
      { title: '常见误区', text: '追求「每块都满分」的完美平衡（不现实）；平衡是动态的补短板，不是永远平均。' },
    ],
    steps: [
      '列出 6-8 个生活维度。',
      '每个 1-10 打分。',
      '连点成轮，看哪里明显凹陷。',
      '给最低 1-2 项各定 1 个本周动作。',
    ],
    tips: [
      '选维度按你真正在意的生活面，不必照搬模板。',
      '复评比一次打分更有价值，能看见趋势。',
    ],
    example: '轮子显示「健康 3、关系 4」偏低：本周定「隔天散步 20 分」「约朋友喝一次茶」。',
    relatedTypes: ['self', 'wellbeing'],
    interactive: true,
    schema: [
      { key: 'dims', label: '生活维度', type: 'textarea', placeholder: '列出 6-8 个你在意的生活维度', rows: 3 },
      { key: 'scores', label: '逐项打分', type: 'textarea', placeholder: '每个维度 1-10 打分', rows: 3 },
      { key: 'plan', label: '补强行动', type: 'textarea', placeholder: '最低 1-2 项各定一个本周动作', rows: 2 },
    ],
  },
  {
    id: 'kpt',
    name: '复盘 KPT',
    icon: '📝',
    color: '#0d9488',
    category: '自我与成长',
    summary: 'Keep 保持–Problem 问题–Try 尝试，轻量复盘让经验沉淀。',
    content: [
      { title: '是什么', text: 'KPT 是敏捷复盘常用法：Keep（继续做的）、Problem（遇到的）、Try（下次尝试的）。' },
      { title: '为什么有用', text: '复盘不为追责，而为把经验变成下次的能力。只靠「感觉还行」会反复踩同样的坑。' },
      { title: '怎么开始', text: '一段经历 / 项目结束后，分三栏写：哪些保留、卡在哪、下次试什么；重点 Try 要具体、可验证。' },
      { title: '常见误区', text: '把 Try 写空（「下次注意」）；或复盘变成批斗会，没人敢说 Problem。' },
    ],
    steps: [
      'K：这次什么做得好，值得保留。',
      'P：具体遇到了什么阻碍或失误。',
      'T：针对 P，下次要试的一个具体动作。',
      '下周 / 下轮对照 T 是否真的做了。',
    ],
    tips: [
      'T 越具体越可查（「提前一天列清单」好过「更认真」）。',
      '个人也适用，睡前 5 分钟就能跑一轮。',
    ],
    example: '项目延期：K=每日站会同步；P=需求中途又加；T=下次先把变更拆小、单独排期。',
    relatedTypes: ['self', 'career'],
    interactive: true,
    schema: [
      { key: 'keep', label: 'K 保持', type: 'textarea', placeholder: '这次什么做得好，值得保留？', rows: 2 },
      { key: 'problem', label: 'P 问题', type: 'textarea', placeholder: '具体遇到了什么阻碍或失误？', rows: 2 },
      { key: 'try', label: 'T 尝试', type: 'textarea', placeholder: '针对问题，下次要试的一个具体动作？', rows: 2 },
    ],
    acronym: [
      { letter: 'K', en: 'Keep', zh: '保持（继续做）' },
      { letter: 'P', en: 'Problem', zh: '问题（遇到了）' },
      { letter: 'T', en: 'Try', zh: '尝试（下次试）' },
    ],
  },
  {
    id: 'swot',
    name: 'SWOT 分析',
    icon: '🧭',
    color: '#4338ca',
    category: '自我与成长',
    summary: '优势/劣势/机会/威胁四象限，做决策与自我定位的框架。',
    content: [
      { title: '是什么', text: 'SWOT：S 优势、W 劣势（内部），O 机会、T 威胁（外部），是做决策与自我定位的经典框架。' },
      { title: '为什么有用', text: '它逼你把「感觉」拆成内外四块，既能看到发力点，也能提前看见风险，避免凭直觉莽撞决定。' },
      { title: '怎么开始', text: '四格各列要点，再用「优势×机会」找突破口、「劣势×威胁」找防御，最后形成行动计划。' },
      { title: '常见误区', text: '只列 S/O 的乐观面，回避 W/T；或列完不行动，停在「分析瘫痪」。' },
    ],
    steps: [
      'S/W：诚实地写自己的内部分别。',
      'O/T：写外部环境的正负因素。',
      '交叉看：S×O 怎么乘势，W×T 怎么防风险。',
      '写出一个「下周就做」的具体动作。',
    ],
    tips: [
      '写 W 时不自我攻击，写 T 时不灾难化，客观即可。',
      '配合测评结果（如 MBTI / 气质）会更准。',
    ],
    example: '想转行：S=沟通强；W=缺证书；O=行业缺人；T=竞争大。行动：先考一个证 + 投缺口岗位。',
    relatedTypes: ['career', 'self', 'personality'],
    interactive: true,
    schema: [
      { key: 's', label: 'S 优势', type: 'textarea', placeholder: '你内部的优势有哪些？', rows: 2 },
      { key: 'w', label: 'W 劣势', type: 'textarea', placeholder: '你内部的劣势有哪些？', rows: 2 },
      { key: 'o', label: 'O 机会', type: 'textarea', placeholder: '外部环境的机会有哪些？', rows: 2 },
      { key: 't', label: 'T 威胁', type: 'textarea', placeholder: '外部环境的威胁有哪些？', rows: 2 },
      { key: 'action', label: '行动计划', type: 'textarea', placeholder: '写出一个「下周就做」的具体动作', rows: 2 },
    ],
    acronym: [
      { letter: 'S', en: 'Strengths', zh: '优势（内部）' },
      { letter: 'W', en: 'Weaknesses', zh: '劣势（内部）' },
      { letter: 'O', en: 'Opportunities', zh: '机会（外部）' },
      { letter: 'T', en: 'Threats', zh: '威胁（外部）' },
    ],
  },
  {
    id: 'sixhats',
    name: '六顶思考帽',
    icon: '🎩',
    color: '#be185d',
    category: '自我与成长',
    summary: '用六顶“帽子”切换视角，避免争辩、全面思考一个问题。',
    content: [
      { title: '是什么', text: '六顶思考帽由 De Bono 提出：白(事实)、红(感受)、黑(风险)、黄(价值)、绿(创意)、蓝(控场)六顶帽代表不同思考角度。' },
      { title: '为什么有用', text: '讨论时常陷入「情绪 vs 事实」混战。一次只戴一顶帽，能把维度拆开，既全面又不打架。' },
      { title: '怎么开始', text: '同一问题依次「戴帽」：先事实、再感受、再找风险与价值、再发散创意、最后蓝帽收束成结论。' },
      { title: '常见误区', text: '六顶帽只用于团队；个人做重大决定时，也能用来自问六个角度，避免片面。' },
    ],
    steps: [
      '白帽：只列事实与数据。',
      '红帽：说出直觉与感受，不需理由。',
      '黑帽：找风险与漏洞（谨慎）。',
      '黄帽 + 绿帽：说价值、再发散新点子；蓝帽收束。',
    ],
    tips: [
      '每个角度都值得被戴到，别跳过黑帽（风险常被美化掉）。',
      '个人决策也可在纸上分六栏自问。',
    ],
    example: '是否辞职创业：白=存款够半年；红=兴奋又怕；黑=没客户风险；黄=自由；绿=先副业试水；蓝=定 3 个月试点。',
    relatedTypes: ['career', 'self'],
    interactive: true,
    schema: [
      { key: 'white', label: '白帽·事实', type: 'textarea', placeholder: '只列事实与数据', rows: 2 },
      { key: 'red', label: '红帽·感受', type: 'textarea', placeholder: '说直觉与感受，不需理由', rows: 2 },
      { key: 'black', label: '黑帽·风险', type: 'textarea', placeholder: '找风险与漏洞（谨慎）', rows: 2 },
      { key: 'yellow', label: '黄帽·价值', type: 'textarea', placeholder: '说价值与乐观面', rows: 2 },
      { key: 'green', label: '绿帽·创意', type: 'textarea', placeholder: '发散新点子', rows: 2 },
      { key: 'blue', label: '蓝帽·收束', type: 'textarea', placeholder: '综合成结论 / 下一步', rows: 2 },
    ],
    acronym: [
      { letter: 'White', en: 'White Hat · Facts', zh: '白帽：事实与数据' },
      { letter: 'Red', en: 'Red Hat · Feelings', zh: '红帽：直觉与感受' },
      { letter: 'Black', en: 'Black Hat · Caution', zh: '黑帽：风险与谨慎' },
      { letter: 'Yellow', en: 'Yellow Hat · Value', zh: '黄帽：价值与乐观' },
      { letter: 'Green', en: 'Green Hat · Creativity', zh: '绿帽：创意与发散' },
      { letter: 'Blue', en: 'Blue Hat · Control', zh: '蓝帽：控场与总结' },
    ],
  },
]

function getMethod(id) {
  return METHODS.find((m) => m.id === id) || null
}
function recommendFor(type, n) {
  const matched = METHODS.filter((m) => (m.relatedTypes || []).includes(type))
  if (matched.length) return n ? matched.slice(0, n) : matched
  // 兜底：无匹配类型（如 intelligence）时，推荐通用自我/幸福感方法
  const fallback = METHODS.filter((m) => (m.relatedTypes || []).some((t) => t === 'self' || t === 'wellbeing'))
  return n ? fallback.slice(0, n) : fallback
}
function groupByCategory() {
  const map = {}
  METHODS.forEach((m) => {
    if (!map[m.category]) map[m.category] = []
    map[m.category].push(m)
  })
  return Object.keys(map).map((c) => ({ category: c, list: map[c] }))
}
module.exports = { METHODS, getMethod, recommendFor, groupByCategory }
