const METHODS = [
  {
    id: 'smart',
    name: 'SMART 目标法',
    icon: '🎯',
    color: '#0891b2',
    category: '目标与行动',
    summary: '把模糊的愿望变成可落地的目标：具体、可衡量、可达、相关、有时限。',
    content: [
      { title: '是什么', text: 'SMART 是目标设定的经典框架，帮助把“我想变好”转化为可执行、可检验的具体目标。' },
      { title: '五要素', text: 'S 具体：目标清晰不笼统；M 可衡量：有量化标准；A 可达：现实可行；R 相关：对你真正重要；T 有时限：明确截止时间。' },
      { title: '怎么用', text: '对照五要素逐条填写，任何一条含糊都要追问细化，例如“多运动”→“每周三、五晚慢跑 30 分钟，持续 8 周”。' },
    ],
    relatedTypes: ['self', 'career', 'wellbeing'],
    interactive: true,
    schema: [
      { key: 'specific', label: 'S 具体', type: 'textarea', placeholder: '目标是什么？要达成什么具体结果？', rows: 2 },
      { key: 'measurable', label: 'M 可衡量', type: 'textarea', placeholder: '如何衡量进度与完成？', rows: 2 },
      { key: 'achievable', label: 'A 可达', type: 'textarea', placeholder: '是否现实？需要哪些资源/支持？', rows: 2 },
      { key: 'relevant', label: 'R 相关', type: 'textarea', placeholder: '为什么这件事对你重要？', rows: 2 },
      { key: 'timebound', label: 'T 有时限', type: 'textarea', placeholder: '何时完成？有哪些关键节点？', rows: 2 },
    ],
  },
  {
    id: 'grow',
    name: 'GROW 教练模型',
    icon: '🌱',
    color: '#059669',
    category: '目标与行动',
    summary: 'Goal 目标–Reality 现状–Options 方案–Will 行动，结构化推进从想法到执行。',
    content: [
      { title: '是什么', text: 'GROW 是全球应用最广的教练对话框架，用四个步骤把模糊的议题梳理成清晰行动。' },
      { title: '四步骤', text: 'G 目标：你想达成什么？R 现状：现在情况如何？O 方案：有哪些可能做法？W 行动：你具体要做什么、何时做？' },
      { title: '怎么用', text: '按顺序回答四个问题，重点在 O 阶段尽量多列方案、不急于否定，W 阶段要落到“具体动作 + 时间”。' },
    ],
    relatedTypes: ['self', 'career', 'wellbeing'],
    interactive: true,
    schema: [
      { key: 'goal', label: 'G 目标', type: 'textarea', placeholder: '你想达成什么？定义清晰、具体的成果。', rows: 3 },
      { key: 'reality', label: 'R 现状', type: 'textarea', placeholder: '现在的情况是怎样的？有哪些已具备的条件？', rows: 3 },
      { key: 'options', label: 'O 方案', type: 'textarea', placeholder: '有哪些可能的做法？先发散，不急着评判。', rows: 3 },
      { key: 'will', label: 'W 行动', type: 'textarea', placeholder: '你具体要做什么？何时开始？如何让自己负责？', rows: 3 },
    ],
  },
  {
    id: 'woop',
    name: 'WOOP 心理对照法',
    icon: '💡',
    color: '#ca8a04',
    category: '目标与行动',
    summary: 'Wish–Outcome–Obstacle–Plan：用“心理对照”把障碍提前想清楚，提升行动力。',
    content: [
      { title: '是什么', text: 'WOOP 由纽约大学 Oettingen 教授基于“心理对照”研究提出：先想结果，再认真想障碍，反而比空想更有效。' },
      { title: '四步骤', text: 'W 愿望：最想实现的改变；O 结果：最好可能的感受/画面；O 障碍：最可能的内部阻碍；P 计划：如果障碍出现，我就……（if-then）。' },
      { title: '关键', text: '把 Plan 写成“如果[障碍]出现，那么我就[具体应对]”，越具体越容易在关键时刻触发。' },
    ],
    relatedTypes: ['self', 'wellbeing', 'career'],
    interactive: true,
    schema: [
      { key: 'wish', label: 'W 愿望', type: 'textarea', placeholder: '你最想做出的一项改变是什么？', rows: 2 },
      { key: 'outcome', label: 'O 结果', type: 'textarea', placeholder: '设想它实现后最好的结果、你的感受？', rows: 2 },
      { key: 'obstacle', label: 'O 障碍', type: 'textarea', placeholder: '最可能出现的内部阻碍是什么？（如拖延、怕失败）', rows: 2 },
      { key: 'plan', label: 'P 计划', type: 'textarea', placeholder: '如果[障碍]出现，那么我就[具体应对]？', rows: 2 },
    ],
  },
  {
    id: 'pomodoro',
    name: '番茄工作法',
    icon: '🍅',
    color: '#dc2626',
    category: '目标与行动',
    summary: '25 分钟专注 + 5 分钟休息的节奏法，降低拖延、提升专注。',
    content: [
      { title: '是什么', text: '由 Francesco Cirillo 提出：把工作切成 25 分钟的高专注段（一个“番茄”），段间短暂休息。' },
      { title: '怎么用', text: '1) 选一项任务；2) 计时 25 分钟只做它；3) 休息 5 分钟；4) 每 4 个番茄长休 15-30 分钟。被打断就记下、稍后处理。' },
      { title: '适用', text: '适合容易分心、拖延或任务庞杂的场景；可用手机计时或小程序计时器配合。' },
    ],
    relatedTypes: ['self', 'career'],
    interactive: false,
  },
  {
    id: 'pdca',
    name: 'PDCA 循环',
    icon: '🔄',
    color: '#0d9488',
    category: '目标与行动',
    summary: 'Plan 计划–Do 执行–Check 检查–Act 处理，持续改进的质量循环。',
    content: [
      { title: '是什么', text: 'PDCA 源于质量管理，也适合个人成长：在“计划—执行—检查—改进”中不断迭代。' },
      { title: '四阶段', text: 'P 制定目标与方案；D 小范围执行；C 对照检查效果与偏差；A 标准化有效做法、修正无效部分，进入下一轮。' },
      { title: '关键', text: '每轮都要有“检查”与“处理”，避免原地打转；改进点进入下一轮 Plan。' },
    ],
    relatedTypes: ['career', 'self'],
    interactive: false,
  },
  {
    id: 'abc',
    name: 'ABC 认知重构',
    icon: '🧩',
    color: '#7c3aed',
    category: '情绪与认知',
    summary: '基于 REBT：情绪不是事件直接造成，而是我们对事件的信念造成。',
    content: [
      { title: '是什么', text: 'Ellis 的理性情绪行为疗法（REBT）用 ABC 模型说明：A 事件→B 信念→C 后果（情绪/行为），并加入 D 辩驳、E 新结果。' },
      { title: '怎么用', text: '当负面情绪出现，记录 A 发生了什么、B 你当时在想什么、C 你的反应；再对 B 做 D 辩驳：有更合理的解读吗？最后写下 E 新结果。' },
      { title: '意义', text: '练习能把“自动化的负面想法”变成可被检验的假设，从而减少被非理性信念牵着走。' },
    ],
    relatedTypes: ['mood', 'stress', 'wellbeing'],
    interactive: true,
    schema: [
      { key: 'event', label: 'A 事件', type: 'textarea', placeholder: '发生了什么？（客观事实）', rows: 2 },
      { key: 'belief', label: 'B 信念', type: 'textarea', placeholder: '你当时在想什么？对自己说了什么？', rows: 2 },
      { key: 'consequence', label: 'C 后果', type: 'textarea', placeholder: '你的情绪与行为反应是什么？', rows: 2 },
      { key: 'dispute', label: 'D 辩驳', type: 'textarea', placeholder: '这个想法证据充分吗？有没有更合理的解释？', rows: 2 },
      { key: 'newresult', label: 'E 新结果', type: 'textarea', placeholder: '辩驳后，你的情绪/行为有什么变化？', rows: 2 },
    ],
  },
  {
    id: 'threegood',
    name: '三件好事',
    icon: '🌟',
    color: '#16a34a',
    category: '情绪与认知',
    summary: '每天记录三件好事并写出原因，训练大脑留意积极面（Seligman 积极心理学练习）。',
    content: [
      { title: '是什么', text: '积极心理学创始人 Seligman 推广的简单练习：连续一段时间，每天写下三件好事及其原因。' },
      { title: '怎么用', text: '睡前回顾当天，写下 3 件进展顺利/让你开心的小事，并回答“为什么会发生”。重点是具体的、哪怕很小的事。' },
      { title: '为什么有效', text: '它能把注意力从问题转向资源，长期练习可提升积极情绪与生活满意度。' },
    ],
    relatedTypes: ['wellbeing', 'mood', 'self'],
    interactive: true,
    schema: [
      { key: 'good1', label: '好事 1', type: 'textarea', placeholder: '今天发生的好事？为什么会发生？', rows: 2 },
      { key: 'good2', label: '好事 2', type: 'textarea', placeholder: '第二件好事？为什么会发生？', rows: 2 },
      { key: 'good3', label: '好事 3', type: 'textarea', placeholder: '第三件好事？为什么会发生？', rows: 2 },
      { key: 'note', label: '今日感悟', type: 'textarea', placeholder: '今天整体的情绪或一句话总结（选填）。', rows: 2 },
    ],
  },
  {
    id: 'mindful',
    name: '正念呼吸',
    icon: '🫧',
    color: '#0891b2',
    category: '情绪与认知',
    summary: '把注意力放回呼吸的觉察练习，帮助从焦虑与反刍中抽离、回到当下。',
    content: [
      { title: '是什么', text: '正念（Mindfulness）源于 MBSR 减压课程：不加评判地觉察当下，呼吸是最常用的锚点。' },
      { title: '怎么练', text: '坐稳、闭眼或垂视；把注意力放在一呼一吸上；走神了就温柔地拉回呼吸。可从 3-5 分钟开始，逐渐延长。' },
      { title: '何时用', text: '焦虑、睡前的念头翻涌、或工作间隙都可做；它不消除情绪，而是改变你与情绪的关系。' },
    ],
    relatedTypes: ['mood', 'stress', 'sleep'],
    interactive: false,
  },
  {
    id: 'nvc',
    name: '非暴力沟通',
    icon: '💬',
    color: '#be185d',
    category: '情绪与认知',
    summary: '观察–感受–需要–请求：用四步表达，减少防御与冲突，增进理解。',
    content: [
      { title: '是什么', text: 'Rosenberg 提出的 NVC：把沟通拆成观察、感受、需要、请求四步，避免评判与指责。' },
      { title: '四步', text: '1 观察：说事实而非贴标签；2 感受：表达情绪而非想法；3 需要：说出未被满足的需要；4 请求：提出具体、可执行的要求。' },
      { title: '怎么用', text: '先区分“观察”和“评价”，用“我感到…因为我需要…”的句式，把指责换成请求。' },
    ],
    relatedTypes: ['social', 'self', 'mood'],
    interactive: false,
  },
  {
    id: 'festinger',
    name: '费斯汀格法则',
    icon: '⚖️',
    color: '#4338ca',
    category: '情绪与认知',
    summary: '生活中 10% 是事件，90% 是你对事件的反应——掌控反应即掌控情绪。',
    content: [
      { title: '是什么', text: '心理学家费斯汀格提出：我们感受到的困扰，只有约 10% 来自事情本身，90% 来自我们对它的反应。' },
      { title: '怎么用', text: '当事情出错，先停顿，问自己“我能控制的是反应而非事件本身”，把精力放在建设性的下一步。' },
      { title: '意义', text: '它提醒情绪的主控权在自己手里：同样的事，不同的解读带来完全不同的结果。' },
    ],
    relatedTypes: ['mood', 'stress', 'self'],
    interactive: false,
  },
  {
    id: 'fogg',
    name: 'Fogg 行为模型',
    icon: '🔧',
    color: '#0d9488',
    category: '习惯与行为',
    summary: 'B=MAP：行为发生需要动机、能力、提示三者同时具备。',
    content: [
      { title: '是什么', text: '斯坦福 BJ Fogg 提出：行为 = 动机(Motivation) × 能力(Ability) × 提示(Prompt)，三者同时出现行为才会发生。' },
      { title: '怎么用', text: '想养成习惯，就从三方面设计：提升动机、降低难度、设置明确提示。动机不足时，优先考虑“让行为更简单”。' },
      { title: '关键', text: '动机和能力强弱可互相补偿：高动机能克服低能力，低动机则需要极低门槛 + 强提示。' },
    ],
    relatedTypes: ['self', 'wellbeing', 'career'],
    interactive: true,
    schema: [
      { key: 'behavior', label: '目标行为', type: 'textarea', placeholder: '你想养成或改变的一个具体行为？', rows: 2 },
      { key: 'motivation', label: '动机强度', type: 'scale', min: 1, max: 10, placeholder: '你做它的意愿有多强？（1-10）' },
      { key: 'ability', label: '容易程度', type: 'scale', min: 1, max: 10, placeholder: '做起来有多容易？（1-10，越高越容易）' },
      { key: 'prompt', label: '提示设计', type: 'textarea', placeholder: '用什么触发来提醒自己执行？（如固定时间/地点/既有动作）', rows: 2 },
      { key: 'design', label: '行动方案', type: 'textarea', placeholder: '如何让行为更容易发生？先从小到不可能失败的一步开始。', rows: 2 },
    ],
  },
  {
    id: 'tinyhabits',
    name: '微习惯',
    icon: '🌰',
    color: '#16a34a',
    category: '习惯与行为',
    summary: '把目标缩到“小到不可能失败”的一步，用锚点习惯串联，轻松启动。',
    content: [
      { title: '是什么', text: 'Fogg 的 Tiny Habits：把新习惯缩小到 30 秒内、几乎零门槛的动作，并“锚定”到一个已有习惯之后。' },
      { title: '配方', text: '“在 [既有习惯] 之后，我会 [微行为]。”例如“刷完牙后，我做 2 个深蹲”。完成后给自己一个肯定。' },
      { title: '为什么有效', text: '低门槛消除了启动阻力与完美主义，先让行为发生，再逐步放大。' },
    ],
    relatedTypes: ['self', 'wellbeing'],
    interactive: false,
  },
  {
    id: 'eisenhower',
    name: '四象限法则',
    icon: '📊',
    color: '#ea580c',
    category: '习惯与行为',
    summary: '按“重要/紧急”把事务分四格，优先做重要不紧急的事。',
    content: [
      { title: '是什么', text: '基于艾森豪威尔矩阵：横轴紧急、纵轴重要，把事务分入四个象限。' },
      { title: '四格', text: '① 重要且紧急：立刻做；② 重要不紧急：排计划重点做（最易被忽略）；③ 紧急不重要：尽量委托/批量；④ 不重要不紧急：减少。' },
      { title: '关键', text: '真正决定长期结果的，是第二象限；把时间前移，减少救火。' },
    ],
    relatedTypes: ['self', 'career'],
    interactive: false,
  },
  {
    id: 'pareto',
    name: '二八定律',
    icon: '⚡',
    color: '#b45309',
    category: '习惯与行为',
    summary: '约 80% 的结果来自 20% 的关键投入，聚焦高杠杆事项。',
    content: [
      { title: '是什么', text: '帕累托法则：在许多领域，约 20% 的原因产生 80% 的结果。' },
      { title: '怎么用', text: '盘点你的任务/客户/时间，找出那 20% 高产出部分，优先投入；对低效的多数做减法或自动化。' },
      { title: '提醒', text: '比例不必精确是 80/20，核心是“少数因素主导结果”，用于识别杠杆点。' },
    ],
    relatedTypes: ['career', 'self'],
    interactive: false,
  },
  {
    id: 'johari',
    name: '乔哈里视窗',
    icon: '🪟',
    color: '#7c3aed',
    category: '自我与成长',
    summary: '公开/盲点/隐藏/未知四个象限，用反馈与自我暴露扩大“公开区”。',
    content: [
      { title: '是什么', text: 'Johari Window 用四个象限描述人际自我认知：公开区（人知我知）、盲点区（人知我不知）、隐藏区（我知人不知）、未知区（人我都不知）。' },
      { title: '怎么用', text: '主动寻求反馈可缩小盲点；适度自我暴露可缩小隐藏区。两者都让“公开区”变大，沟通与信任更顺畅。' },
      { title: '意义', text: '它帮你看清“别人眼中的我”与“我眼中的我”的差距，是自我认知与关系改善的地图。' },
    ],
    relatedTypes: ['social', 'self', 'personality'],
    interactive: true,
    schema: [
      { key: 'open', label: '公开区', type: 'textarea', placeholder: '别人知道、你也知道的优点/特点？', rows: 2 },
      { key: 'blind', label: '盲点区', type: 'textarea', placeholder: '你不太察觉、但别人可能注意到的？', rows: 2 },
      { key: 'hidden', label: '隐藏区', type: 'textarea', placeholder: '你隐瞒、尚未对他人说的？（选填）', rows: 2 },
      { key: 'unknown', label: '未知区', type: 'textarea', placeholder: '你想探索的潜能或盲区？', rows: 2 },
    ],
  },
  {
    id: 'perma',
    name: 'PERMA 积极心理学',
    icon: '🌈',
    color: '#db2777',
    category: '自我与成长',
    summary: '积极情绪、投入、关系、意义、成就——幸福五要素自评与练习。',
    content: [
      { title: '是什么', text: 'Seligman 把幸福拆成五个可培养的元素：P 积极情绪、E 投入、R 关系、M 意义、A 成就。' },
      { title: '怎么用', text: '对每个维度 1-10 自评，找出最薄弱的一环，针对性地安排活动（如关系弱就约朋友、意义弱就做志愿）。' },
      { title: '意义', text: '幸福不是单一情绪，而是多维度均衡；刻意练习每个要素都能提升整体幸福感。' },
    ],
    relatedTypes: ['wellbeing', 'mood', 'self'],
    interactive: true,
    schema: [
      { key: 'positive', label: 'P 积极情绪', type: 'scale', min: 1, max: 10, placeholder: '近期体验愉悦/满足的程度（1-10）' },
      { key: 'engagement', label: 'E 投入', type: 'scale', min: 1, max: 10, placeholder: '专注忘我做事的程度（1-10）' },
      { key: 'relationship', label: 'R 关系', type: 'scale', min: 1, max: 10, placeholder: '与他人联结/被支持的程度（1-10）' },
      { key: 'meaning', label: 'M 意义', type: 'scale', min: 1, max: 10, placeholder: '觉得所作所为有意义程度（1-10）' },
      { key: 'accomplishment', label: 'A 成就', type: 'scale', min: 1, max: 10, placeholder: '达成目标/有成就感程度（1-10）' },
      { key: 'note', label: '薄弱项计划', type: 'textarea', placeholder: '最弱的一项打算如何加强？（选填）', rows: 2 },
    ],
  },
  {
    id: 'growth',
    name: '成长型思维',
    icon: '🌿',
    color: '#059669',
    category: '自我与成长',
    summary: '能力可通过努力与策略发展，把“我不行”换成“我还没学会”。',
    content: [
      { title: '是什么', text: 'Dweck 提出：固定型思维认为能力天生，成长型思维认为能力可经练习生长。' },
      { title: '怎么用', text: '遇到挫折时，把“我做不到”改为“我目前还做不到，需要____”。把挑战当练习而非对智力的审判。' },
      { title: '关键', text: '夸努力与策略，而非“你真聪明”；对失败的好奇心比一次成功更重要。' },
    ],
    relatedTypes: ['self', 'wellbeing', 'career'],
    interactive: false,
  },
  {
    id: 'flow',
    name: '心流',
    icon: '🌊',
    color: '#0891b2',
    category: '自我与成长',
    summary: '挑战与技能匹配时进入的完全专注状态，是高效与幸福的来源。',
    content: [
      { title: '是什么', text: 'Csikszentmihalyi 提出：当任务挑战与自身技能大致匹配，人会进入忘我、时间感改变的深度专注状态。' },
      { title: '怎么用', text: '主动调节任务难度：太易会无聊、太难会焦虑；设定清晰目标与即时反馈，更容易进入心流。' },
      { title: '意义', text: '心流体验本身即奖赏，也是创造力与满足感的重要来源。' },
    ],
    relatedTypes: ['wellbeing', 'self'],
    interactive: false,
  },
  {
    id: 'wheel',
    name: '人生平衡轮',
    icon: '🎡',
    color: '#ca8a04',
    category: '自我与成长',
    summary: '从多个生活维度打分，看见失衡处，制定补强行动。',
    content: [
      { title: '是什么', text: '把生活分成若干维度（如健康、事业、关系、成长等），每个 1-10 打分并连成“轮子”，直观看哪里瘸腿。' },
      { title: '怎么用', text: '先给各维度打分，找出最低的几项，各写 1 个可落地的提升动作，下周复评。' },
      { title: '意义', text: '平衡不是平均，而是让你清楚“此刻最该补哪块”，避免长期偏科。' },
    ],
    relatedTypes: ['self', 'wellbeing'],
    interactive: false,
  },
  {
    id: 'kpt',
    name: '复盘 KPT',
    icon: '📝',
    color: '#0d9488',
    category: '自我与成长',
    summary: 'Keep 保持–Problem 问题–Try 尝试，轻量复盘让经验沉淀。',
    content: [
      { title: '是什么', text: 'KPT 是敏捷复盘常用法：Keep（继续做的）、Problem（遇到的）、Try（下次尝试的）。' },
      { title: '怎么用', text: '项目或一段经历结束后，分别列出 K/P/T 三栏，重点在 Try 要具体、可验证，下次对照检查。' },
      { title: '关键', text: '复盘不为追责，而为学习；Try 越具体，下一轮改进越容易。' },
    ],
    relatedTypes: ['self', 'career'],
    interactive: false,
  },
  {
    id: 'swot',
    name: 'SWOT 分析',
    icon: '🧭',
    color: '#4338ca',
    category: '自我与成长',
    summary: '优势/劣势/机会/威胁四象限，做决策与自我定位的框架。',
    content: [
      { title: '是什么', text: 'SWOT：S 优势、W 劣势（内部），O 机会、T 威胁（外部），常用于个人规划与决策。' },
      { title: '怎么用', text: '四格各列要点，再用“优势×机会”找发力点、“劣势×威胁”找风险，形成行动计划。' },
      { title: '适用', text: '职业选择、项目立项、年度规划都可用；配合结果页的 MBTI/气质测评效果更佳。' },
    ],
    relatedTypes: ['career', 'self', 'personality'],
    interactive: false,
  },
  {
    id: 'sixhats',
    name: '六顶思考帽',
    icon: '🎩',
    color: '#be185d',
    category: '自我与成长',
    summary: '用六顶“帽子”切换视角，避免争辩、全面思考一个问题。',
    content: [
      { title: '是什么', text: 'De Bono 的方法：白(事实)、红(感受)、黑(风险)、黄(价值)、绿(创意)、蓝(控场)六顶帽代表不同思考角度。' },
      { title: '怎么用', text: '同一问题依次“戴上”各帽：先事实、再感受、再找风险与价值、再发散创意、最后蓝帽收束。' },
      { title: '关键', text: '一次只戴一顶，避免情绪与事实混战；它让团队/个人把思考维度拆开。' },
    ],
    relatedTypes: ['career', 'self'],
    interactive: false,
  },
]

function getMethod(id) {
  return METHODS.find((m) => m.id === id) || null
}
function recommendFor(type, n) {
  const matched = METHODS.filter((m) => (m.relatedTypes || []).includes(type))
  if (matched.length) return n ? matched.slice(0, n) : matched
  // 兜底：无匹配类型（如 intelligence）时，推荐通用自我/幸福感方法
  const fallback = METHODS.filter((m) => (m.relatedTypes || []).some((t) => t === 'self' || t === 'wellbeing'))
  return n ? fallback.slice(0, n) : fallback
}
function groupByCategory() {
  const map = {}
  METHODS.forEach((m) => {
    if (!map[m.category]) map[m.category] = []
    map[m.category].push(m)
  })
  return Object.keys(map).map((c) => ({ category: c, list: map[c] }))
}
module.exports = { METHODS, getMethod, recommendFor, groupByCategory }
